---
include:
  - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/recipes/debian.yml

variables:
  SALSA_CI_AUTOPKGTEST_ARGS: '--no-auto-control'
  SALSA_CI_DISABLE_BUILD_PACKAGE_I386: 1
  SALSA_CI_ENABLE_BUILD_PACKAGE_TWICE: 1

blhc:
  allow_failure: true
